#!/usr/bin/env python3
"""Generate independent UPER fixture bytes and bit lengths with asn1tools."""
from __future__ import annotations

import hashlib
import json
from pathlib import Path

import asn1tools
from asn1tools.codecs.uper import Encoder

from fixture_values import FIXTURES, NEGATIVE

ROOT = Path(__file__).resolve().parents[4]
ASN1 = ROOT / "docs/specs/asn1/lpp/r16.4.0/modules_v2/subsets/minimum-envelope/LPP-PDU-Definitions.asn1"
OUT = ROOT / "tools/specs/lpp/fixtures/r16.4.0"
LOCK = ROOT / "tools/specs/lpp/reference-codec/requirements-lock.txt"


def sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def jsonable(value):
    if isinstance(value, tuple):
        return [jsonable(item) for item in value]
    if isinstance(value, dict):
        return {key: jsonable(item) for key, item in value.items()}
    if isinstance(value, list):
        return [jsonable(item) for item in value]
    return value


def encode_with_bits(specification, type_name, value):
    # Run the compiler's public constraint checker before using its encoder
    # instrumentation for pre-octet-padding bit length.
    public_encoded = bytes(specification.encode(type_name, value, check_constraints=True))
    compiled = specification.types[type_name]
    encoder = Encoder()
    compiled._type.encode(value, encoder)  # asn1tools UPER instrumentation, not a production codec.
    bit_length = encoder.chunks_number_of_bits + encoder.number_of_bits
    encoded = bytes(encoder.as_bytearray())
    if encoded != public_encoded:
        raise SystemExit(f"internal/public encoder mismatch for {type_name}")
    return encoded, bit_length


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    specification = asn1tools.compile_files([str(ASN1)], codec="uper")
    records = []
    for name, (type_name, value, purpose) in FIXTURES.items():
        encoded, bits = encode_with_bits(specification, type_name, value)
        decoded = specification.decode(type_name, encoded)
        reencoded, rebits = encode_with_bits(specification, type_name, decoded)
        if encoded != reencoded or bits != rebits or jsonable(decoded) != jsonable(value):
            raise SystemExit(f"round-trip mismatch: {name}")
        input_file = OUT / f"{name}.input.py"
        binary_file = OUT / f"{name}.uper"
        input_file.write_text("# Generated fixture source value; Python tuple denotes ASN.1 CHOICE.\nVALUE = " + repr(value) + "\n", encoding="utf-8")
        binary_file.write_bytes(encoded)
        records.append({"name": name, "top_level_type": type_name, "purpose": purpose,
                        "source_value_file": input_file.name, "binary_file": binary_file.name,
                        "hex": encoded.hex(), "bit_length": bits, "unused_trailing_bits": len(encoded) * 8 - bits,
                        "decoded_value": jsonable(decoded), "round_trip": "byte-and-bit-identical"})
    negatives = []
    for name, (type_name, value) in NEGATIVE.items():
        try:
            encode_with_bits(specification, type_name, value)
        except Exception as exc:
            negatives.append({"name": name, "rejected": True, "error_type": type(exc).__name__, "error": str(exc)})
        else:
            negatives.append({"name": name, "rejected": False, "error": "compiler accepted invalid test value"})
    manifest = {"specification": "3GPP TS 37.355 V16.4.0", "encoding_rule": "uper", "compiler": "asn1tools",
                "compiler_version": asn1tools.__version__, "module": str(ASN1.relative_to(ROOT)),
                "module_sha256": sha(ASN1), "dependency_lock_sha256": sha(LOCK), "fixtures": records,
                "negative_cases": negatives, "bit_length_method": "asn1tools.codecs.uper.Encoder pre-octet-padding bit count"}
    (OUT / "manifest.json").write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    (OUT / "README.md").write_text("# Independent TS 37.355 UPER fixtures\n\nGenerated by the pinned development-only `asn1tools` UPER compiler. Bit length is measured before transport-octet padding; `.uper` stores the padded octets and the manifest records the number of unused trailing bits. These are codec-mechanics fixtures, not positioning results.\n", encoding="utf-8")
    print(f"generated {len(records)} valid fixtures and {len(negatives)} negative cases")


if __name__ == "__main__":
    main()
