package lppa

import (
	"bytes"
	"os"
	"path/filepath"
	"testing"

	"github.com/vectorcore/esmlc/internal/aper"
)

// These files are generated by the repository-local independent TS 36.455
// APER fixture encoder (tools/specs/lppa/reference-codec/generate.py). This
// test compares complete PDUs, not IE fragments, and every fixture is also
// round-tripped through Decode to exercise the reader path.
func TestTS36455CompleteMessageFixtures(t *testing.T) {
	periodicMS1024 := PeriodicityMS1024
	accessPoint := AccessPointPosition{
		Latitude: 38, Longitude: -90, Depth: false, Altitude: 120,
		UncertaintySemiMajor: 10, UncertaintySemiMinor: 5, OrientationOfMajorAxis: 45, UncertaintyAltitude: 3, Confidence: 68,
	}
	resultMinimal := ECIDMeasurementResult{
		ServingCellID:  ECGI{PLMNIdentity: [3]byte{0x00, 0xf1, 0x10}, CellIdentity: 0x0abcdef},
		ServingCellTAC: [2]byte{0x10, 0x01},
	}
	resultWithPosition := resultMinimal
	resultWithPosition.AccessPointPosition = &accessPoint

	cases := map[string]func() (PDU, error){
		"initiation-request-ondemand": func() (PDU, error) {
			return BuildInitiationRequest(1, 3, ReportOnDemand, nil, []MeasurementQuantityValue{QuantityCellID})
		},
		"initiation-request-periodic": func() (PDU, error) {
			return BuildInitiationRequest(2, 5, ReportPeriodic, &periodicMS1024, []MeasurementQuantityValue{QuantityCellID})
		},
		"initiation-response-minimal": func() (PDU, error) {
			mid3, err := EncodeMeasurementID(3)
			if err != nil {
				return PDU{}, err
			}
			mid9, err := EncodeMeasurementID(9)
			if err != nil {
				return PDU{}, err
			}
			return PDU{Category: Successful, ProcedureCode: ProcedureECIDMeasurementInitiation, Criticality: aper.Reject, TransactionID: 1, IEs: []IE{
				{IEESMLCMeasurementID, aper.Reject, mid3},
				{IEENBMeasurementID, aper.Reject, mid9},
			}}, nil
		},
		"initiation-response-full": func() (PDU, error) {
			mid5, err := EncodeMeasurementID(5)
			if err != nil {
				return PDU{}, err
			}
			mid11, err := EncodeMeasurementID(11)
			if err != nil {
				return PDU{}, err
			}
			result, err := EncodeECIDMeasurementResult(resultWithPosition)
			if err != nil {
				return PDU{}, err
			}
			cellPortion, err := EncodeCellPortionID(12)
			if err != nil {
				return PDU{}, err
			}
			return PDU{Category: Successful, ProcedureCode: ProcedureECIDMeasurementInitiation, Criticality: aper.Reject, TransactionID: 2, IEs: []IE{
				{IEESMLCMeasurementID, aper.Reject, mid5},
				{IEENBMeasurementID, aper.Reject, mid11},
				{IECIDMeasurementResult, aper.Ignore, result},
				{IECellPortionID, aper.Ignore, cellPortion},
			}}, nil
		},
		"initiation-failure-misc-unspecified": func() (PDU, error) {
			mid3, err := EncodeMeasurementID(3)
			if err != nil {
				return PDU{}, err
			}
			cause, err := EncodeCause(Cause{CauseMisc, 0})
			if err != nil {
				return PDU{}, err
			}
			return PDU{Category: Unsuccessful, ProcedureCode: ProcedureECIDMeasurementInitiation, Criticality: aper.Reject, TransactionID: 1, IEs: []IE{
				{IEESMLCMeasurementID, aper.Reject, mid3},
				{IECause, aper.Ignore, cause},
			}}, nil
		},
		"initiation-failure-radio-network-unspecified": func() (PDU, error) {
			mid7, err := EncodeMeasurementID(7)
			if err != nil {
				return PDU{}, err
			}
			cause, err := EncodeCause(Cause{CauseRadioNetwork, 0})
			if err != nil {
				return PDU{}, err
			}
			return PDU{Category: Unsuccessful, ProcedureCode: ProcedureECIDMeasurementInitiation, Criticality: aper.Reject, TransactionID: 3, IEs: []IE{
				{IEESMLCMeasurementID, aper.Reject, mid7},
				{IECause, aper.Ignore, cause},
			}}, nil
		},
		"failure-indication-protocol-semantic-error": func() (PDU, error) {
			mid9, err := EncodeMeasurementID(9)
			if err != nil {
				return PDU{}, err
			}
			mid11, err := EncodeMeasurementID(11)
			if err != nil {
				return PDU{}, err
			}
			cause, err := EncodeCause(Cause{CauseProtocol, 4})
			if err != nil {
				return PDU{}, err
			}
			return PDU{Category: Initiating, ProcedureCode: ProcedureECIDMeasurementFailureIndication, Criticality: aper.Ignore, TransactionID: 4, IEs: []IE{
				{IEESMLCMeasurementID, aper.Reject, mid9},
				{IEENBMeasurementID, aper.Reject, mid11},
				{IECause, aper.Ignore, cause},
			}}, nil
		},
		"report-with-cell-portion": func() (PDU, error) {
			mid9, err := EncodeMeasurementID(9)
			if err != nil {
				return PDU{}, err
			}
			mid11, err := EncodeMeasurementID(11)
			if err != nil {
				return PDU{}, err
			}
			result, err := EncodeECIDMeasurementResult(resultMinimal)
			if err != nil {
				return PDU{}, err
			}
			cellPortion, err := EncodeCellPortionID(200)
			if err != nil {
				return PDU{}, err
			}
			return PDU{Category: Initiating, ProcedureCode: ProcedureECIDMeasurementReport, Criticality: aper.Ignore, TransactionID: 5, IEs: []IE{
				{IEESMLCMeasurementID, aper.Reject, mid9},
				{IEENBMeasurementID, aper.Reject, mid11},
				{IECIDMeasurementResult, aper.Ignore, result},
				{IECellPortionID, aper.Ignore, cellPortion},
			}}, nil
		},
		"report-without-cell-portion": func() (PDU, error) {
			mid3, err := EncodeMeasurementID(3)
			if err != nil {
				return PDU{}, err
			}
			mid9, err := EncodeMeasurementID(9)
			if err != nil {
				return PDU{}, err
			}
			result, err := EncodeECIDMeasurementResult(resultWithPosition)
			if err != nil {
				return PDU{}, err
			}
			return PDU{Category: Initiating, ProcedureCode: ProcedureECIDMeasurementReport, Criticality: aper.Ignore, TransactionID: 6, IEs: []IE{
				{IEESMLCMeasurementID, aper.Reject, mid3},
				{IEENBMeasurementID, aper.Reject, mid9},
				{IECIDMeasurementResult, aper.Ignore, result},
			}}, nil
		},
		"termination": func() (PDU, error) {
			return BuildTerminationCommand(1, 3, 9)
		},
	}

	for name, build := range cases {
		t.Run(name, func(t *testing.T) {
			expected, err := os.ReadFile(filepath.Join("..", "..", "tools", "specs", "lppa", "fixtures", "r16.0.0", name+".aper"))
			if err != nil {
				t.Fatal(err)
			}
			pdu, err := build()
			if err != nil {
				t.Fatalf("build: %v", err)
			}
			got, err := Encode(pdu)
			if err != nil {
				t.Fatalf("encode: %v", err)
			}
			if !bytes.Equal(got, expected) {
				t.Fatalf("wire mismatch\n got %x\nwant %x", got, expected)
			}
			decoded, err := Decode(got)
			if err != nil {
				t.Fatalf("decode: %v", err)
			}
			if decoded.Category != pdu.Category || decoded.ProcedureCode != pdu.ProcedureCode || decoded.Criticality != pdu.Criticality || decoded.TransactionID != pdu.TransactionID {
				t.Fatalf("decoded envelope mismatch: %+v vs %+v", decoded, pdu)
			}
			if len(decoded.IEs) != len(pdu.IEs) {
				t.Fatalf("decoded IE count mismatch: %d vs %d", len(decoded.IEs), len(pdu.IEs))
			}
		})
	}
}
