package lcsap

import (
	"bytes"
	"os"
	"path/filepath"
	"testing"

	"github.com/vectorcore/esmlc/internal/aper"
)

// These files are generated by the repository-local independent TS 29.171
// APER fixture encoder. This test compares complete PDUs, not IE fragments.
func TestTS29171CompleteMessageFixtures(t *testing.T) {
	id := [4]byte{0, 0, 0, 1}
	data := NewECIDPositioningData()
	fulfilled := AccuracyFulfilled
	responses := map[string]func() ([]byte, error){
		"success-location-estimate": func() ([]byte, error) { return LocationResponse(id, 38, -90, 4) },
		"success-positioning-data": func() ([]byte, error) {
			return Encode(PDU{Successful, ProcedureLocationRequest, aper.Reject, []IE{{IECorrelationID, aper.Reject, id[:]}, {IEPositioningData, aper.Reject, mustPositioning(t, data)}}})
		},
		"success-accuracy-fulfilled": func() ([]byte, error) {
			return Encode(PDU{Successful, ProcedureLocationRequest, aper.Reject, []IE{{IECorrelationID, aper.Reject, id[:]}, {IEAccuracyFulfillmentIndicator, aper.Reject, []byte{0}}}})
		},
		"success-accuracy-not-fulfilled": func() ([]byte, error) {
			return Encode(PDU{Successful, ProcedureLocationRequest, aper.Reject, []IE{{IECorrelationID, aper.Reject, id[:]}, {IEAccuracyFulfillmentIndicator, aper.Reject, []byte{0x40}}}})
		},
		"success-estimate-positioning-data":       func() ([]byte, error) { return LocationResponseWithMetadata(id, 38, -90, 4, &data, nil) },
		"success-authoritative-serving-cell-ecid": func() ([]byte, error) { return LocationResponseWithMetadata(id, 38, -90, 4, &data, &fulfilled) },
		"failure-radio-network-unspecified": func() ([]byte, error) {
			return FailureWithDetailedCause(id, LCSCause{LCSCauseRadioNetwork, RadioNetworkUnspecified})
		},
		"failure-transport-resource-unavailable": func() ([]byte, error) {
			return FailureWithDetailedCause(id, LCSCause{LCSCauseTransport, TransportResourceUnavailable})
		},
		"failure-protocol-semantic-error": func() ([]byte, error) {
			return FailureWithDetailedCause(id, LCSCause{LCSCauseProtocol, ProtocolSemanticError})
		},
		"failure-misc-unspecified": func() ([]byte, error) { return FailureWithDetailedCause(id, LCSCause{LCSCauseMisc, MiscUnspecified}) },
	}
	for name, encode := range responses {
		expected, err := os.ReadFile(filepath.Join("..", "..", "tools", "specs", "lcsap", "fixtures", "r16.4.0", name+".aper"))
		if err != nil {
			t.Fatal(err)
		}
		got, err := encode()
		if err != nil {
			t.Fatalf("%s: %v", name, err)
		}
		if !bytes.Equal(got, expected) {
			t.Fatalf("%s wire mismatch\n got %x\nwant %x", name, got, expected)
		}
	}
}

func mustPositioning(t *testing.T, data PositioningData) []byte {
	t.Helper()
	b, err := data.EncodeAPER()
	if err != nil {
		t.Fatal(err)
	}
	return b
}
